# -*- coding: utf-8 -*-
"""Introduction to Data Science .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k3dwrIioGc3BrR4BxtcolQwvSjSzII-G

**DataSet**
"""

X = [[25,30],[35,45],[45,60],[20,20],
     [50,50],[60,45],[30,25],[40,60]]
y = [0, 1, 1, 0, 1, 0, 0, 1]
# Features: [Age, Spending Score]
# Labels: 0=No Purchase, 1=Purchase

"""**1**. **Data** **Preprocessing**"""

import numpy as np

X = np.array([[25,30],[35,45],[45,60],[20,20],[50,50],[60,45],[30,25],[40,60]])
y = np.array([0,1,1,0,1,0,0,1])

# Standardize: zero mean, unit variance
mean = X.mean(axis=0)
std  = X.std(axis=0)
X_scaled = (X - mean) / std

# 75/25 split (6 train, 2 test)
X_train, X_test = X_scaled[:6], X_scaled[6:]
y_train, y_test = y[:6], y[6:]

"""**2**. **Model** **implementation**"""

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def compute_cost(X, y, w, b):
    m = len(y)
    yhat = sigmoid(X @ w + b)
    return (-y * np.log(yhat) - (1 - y) * np.log(1 - yhat)).mean()

def gradient_descent(X, y, lr=0.1, iters=1000):
    m, n = X.shape
    w, b = np.zeros(n), 0.0
    costs = []
    for i in range(iters):
        yhat = sigmoid(X @ w + b)
        err  = yhat - y
        w   -= lr * (X.T @ err) / m   # weight gradient
        b   -= lr * err.mean()         # bias gradient
        if i % 100 == 0:
            costs.append(compute_cost(X, y, w, b))
    return w, b, costs

"""**3. Training**"""

w, b, costs = gradient_descent(X_train, y_train, lr=0.1, iters=1000)
print(f"Weights: {w}  |  Bias: {b:.4f}")

"""**4. Evaluate & plot decision boundary**"""

import matplotlib.pyplot as plt

def predict(X, w, b):
    return (sigmoid(X @ w + b) >= 0.5).astype(int)

y_pred = predict(X_test, w, b)
accuracy = (y_pred == y_test).mean() * 100
print(f"Test accuracy: {accuracy}%")

# Decision boundary: w0*x1 + w1*x2 + b = 0  →  x2 = -(w0*x1 + b) / w1
x1 = np.linspace(X_scaled[:,0].min()-0.5, X_scaled[:,0].max()+0.5, 100)
x2 = -(w[0]*x1 + b) / w[1]

plt.figure(figsize=(7,5))
plt.scatter(X_train[y_train==0,0], X_train[y_train==0,1], color='red',  label='No Purchase (0)', s=80)
plt.scatter(X_train[y_train==1,0], X_train[y_train==1,1], color='blue', label='Purchase (1)',    s=80)
plt.plot(x1, x2, 'k--', label='Decision boundary')
plt.xlabel('Age (standardized)'); plt.ylabel('Spending Score (standardized)')
plt.legend(); plt.title('Logistic Regression — Decision Boundary')
plt.tight_layout(); plt.show()

"""**5. Compare with scikit-learn**"""

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state=0)
clf.fit(X_train, y_train)
sk_acc = clf.score(X_test, y_test) * 100
print(f"Custom Model accuracy : {accuracy}%")
print(f"Scikit-Learn Model accuracy  : {sk_acc}%")